version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
  pubsub:
    build:
      context: .
      dockerfile: Dockerfile.emu
    restart: always
    environment:
      - PROJECT_ID=emulator
      - TOPIC_ID=event-topic-local
      - SUBSCRIPTION_ID=event-subscription-local
      - PUSH_ENDPOINT=http://host.docker.internal:3000/example
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8085:8085
  publisher:
    image: golang:1.19
    build:
      context: ..
    environment:
      - PFUNC="p"
      - PUBSUB_EMULATOR_HOST=pubsub:8085
      - PROJECT_ID=emulator
    volumes:
      - .:/tmp
    depends_on:
      - pubsub
  subscriber:
    image: golang:1.19
    build:
      context: ..
    depends_on:
      - pubsub
      - redis
    volumes:
        - .:/tmp
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub:8085
      - PROJECT_ID=emulator
  test:
    image: golang:1.19
    depends_on:
      - pubsub
      - redis
    volumes:
        - ../:/go/src
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub:8085
      - PROJECT_ID=emulator





